name: Testing
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run application tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3
      - name: Install and configure Poetry
        run: pipx install poetry

      - name: Install Python
        id: install-python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # pin@v4
        with:
          cache: "poetry"
          python-version: '3.10' 

      - name: Check cache hit
        run: echo '${{ steps.install-python.outputs.cache-hit }}' # true if cache-hit occured on the primary key

      - name: Install dependencies
        run: |
          poetry env use '${{ steps.install-python.outputs.python-path }}'
          poetry install --no-interaction --no-root

      - name: Run tests
        run: |
          set -o pipefail
          poetry run pytest --cov-report=xml --cov=fastapi_qp test/

      - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # pin@v2
        with:
          files: ./coverage.xml
